### ISSUE TITLE
The plugin quick start doesn't work

### ISSUE THREAD

**Issue by numediaweb** [shopware/devdocs#87] opened 2015-07-06 10:00 UTC
I followed the steps on [the plugin quickstart](https://github.com/shopware/devdocs/blob/master/source/developers-guide/plugin-quick-start/index.md) but I couldn't see the results displayed on the front end.

I switched back and forth the Bar theme and Responsive theme but none of them was able to show the  Slogan widget in the frontend.

I even deleted my plugin and used the one [you provided ](https://developers.shopware.com/exampleplugins/SwagSloganOfTheDay.zip) but it also didn't work!

I cheked the logs and couldn't see anything suspesious :(

I'm running Shopware 5 on localhost on a windows 7 machine.

**Comment by tiagojsag** [comment] 2015-07-06 11:40
Hi, @numediaweb 

I just tested the example plugin package we provide (the one you linked) and it works as intended.

Please be sure to clear the caches (backend => "Configuration" => "Cache/performance" =>  "Cache") after installing the plugin. Also, make sure the plugin itself is both installed and active. Should you have additional problems, please check our forum for support. 

Closing

**Closed by tiagojsag** 2015-07-06 11:40 UTC

**Comment by numediaweb** [comment] 2015-07-06 12:13
Thanks @tiagojsag  I already cleared the cache and even deleted the cache folder and cleared browser cache. However I couldn't see the slogan text on the frontend.

Is there any menu or setting that I should activate? i don't have ionCube extension on my localhost; is this a problem?

**Comment by tiagojsag** [comment] 2015-07-06 12:19
The ioncube extension is only needed for plugins downloaded from the store. This is not the case.

**Comment by numediaweb** [comment] 2015-07-06 12:29
I think there's something wrong with Shopware system; it must work on first clean install or at least give a warning/log if a problem happens.

I have to develop a small plugin for a client but seems complicated without debugging why the template is not loaded and why it doesn't modify the `responsive` one.

**Comment by numediaweb** [comment] 2015-07-06 12:30
Also this is not a good way to encourage third parties to develop plugins for Shopware if the provided example doesn't work on a clean install!

**Comment by tiagojsag** [comment] 2015-07-06 12:41
Hello again,

Like I mentioned before, I tested the scenario you described, and I had no problems reproducing the behaviour described in the documentation. Also, AFAIK, there are no additional reports of this issue affecting anyone else, so a bug in Shopware itself seems unlikely at this point.

You mentioned you are using Windows, which is not officially supported: https://developers.shopware.com/sysadmins-guide/system-requirements/

As I mentioned before, the issue here is not related to the devdocs themselves, nor is this repository intended to be a support medium for Shopware. Please refer additional questions/findings to the forum.

**Comment by numediaweb** [comment] 2015-07-06 13:36
Thanks @tiagojsag I opened [a ticket](http://forum.shopware.com/general-f72/the-plugin-quick-start-doesn-t-work-t29090.html) in the forums. I'am testing now on a live server running Linux; If it doesn't work on first install then I guess, Shopware is not a serious software.

**Comment by numediaweb** [comment] 2015-07-06 13:45
After testing on the remote server, running Linux, the plugin works! First time to face such a limitation on a CMS/Shopsystem.

**Comment by sarathiscookie** [comment] 2015-12-03 10:41
I have configured shopware 5.1.1 in windows 7 and installed sample plugin shown in shopware doc. But it is not working. I have clear the cache.

**Comment by zkov** [comment] 2017-03-07 22:47
Yep, same problem. Win 10, fresh install.

**Comment by sarathiscookie** [comment] 2017-03-14 17:32
@zkov I faced the same issue few months before. I followed this url "https://forum.shopware.com/discussion/29090/the-plugin-quick-start-doesnt-work".  Plugin quick start is working for me. I am using windows 10 and xampp.

**Comment by shahidkarimi** [comment] 2017-11-20 19:42
Shopware is just a piece of shit. No community support, limited community, documentation is very insufficient, things don't work as explained. Please abandon it there are lot of world-class e-commerce flatforms already.

**Comment by tkapet** [comment] 2017-12-15 17:10
I have also experienced problems that plugin templates do not work under WINDOWS.
The same exactly code in my mac & linux system is working fine.

**Comment by mitelg** [comment] 2017-12-18 10:11
hello @tkapet 
there are known issues with windows server systems. but we do not officially support Windows.

greetings
