### ISSUE TITLE
Plugin quick start not working

### ISSUE THREAD

**Issue by sarathiscookie** [shopware/devdocs#195] opened 2015-12-03 10:43 UTC
I have configured shopware 5.1.1 in windows 7 and installed sample plugin shown in shopware doc. But it is not working. I have clear the cache.

**Comment by tiagojsag** [comment] 2015-12-03 10:45
Hi,

This is a duplicate of https://github.com/shopware/devdocs/issues/87

closing

**Closed by tiagojsag** 2015-12-03 10:45 UTC
